### PR TITLE
About-Page update + Discord link

### PR DESCRIPTION
**Pull request by alpinho**
This PR is not finished, yet. Waiting for Stephanie's profile.

### CODE REVIEW

**Comment by alpinho** [comment]
This PR includes:
1. updates in the about page w/ new profiles
2. updates in the slide to download
3. renaming some files (better name, e.g. snake case)
4. block-name corrections in the about page
5. added discord link to footer

**Review by anibalsolon — APPROVED** [review]
LGTM!

**Comment by anibalsolon** [comment]
Just updated some missing diacritics in the `alt` image attributes.

**Comment by alpinho** [comment]
I actually changed the alt field with the corresponding names but without accents. But it seems you changed that back specifically for Fabio's profile.

**Pull request merged**
